import "dotenv/config";
import { drizzle } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";

import * as schema from "../db/schema";

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql, { schema });

const main = async () => {
    try {
        console.log("Seeding Database");

        // Clear existing data
        await db.delete(schema.courses);
        await db.delete(schema.units);
        await db.delete(schema.lessons);
        await db.delete(schema.challenges);
        await db.delete(schema.challengeOptions);
        await db.delete(schema.challengeProgress);

        // Insert courses
        await db.insert(schema.courses).values([
            { id: 1, title: "Stocks", imageSrc: "/stock.png" },
            { id: 2, title: "Budgeting", imageSrc: "/budget.png" },
            { id: 3, title: "Loans & Debts", imageSrc: "/loan.png" },
            { id: 4, title: "Investment", imageSrc: "/investment.png" },
            { id: 5, title: "Bank", imageSrc: "/bank.png" },
            { id: 6, title: "Financial Goals", imageSrc: "/finance.png" },
            { id: 7, title: "Insurance", imageSrc: "/insurance.png" },
            { id: 8, title: "Retirement", imageSrc: "/retirement.png" },
            {id: 9, title: "Challenges", imageSrc: "/challenge.png"}
        ]);

        //units
        await db.insert(schema.units).values([
            { id: 1, courseId: 1, title: "Unit 1", description: "Learn the basics of Stocks", order: 1 },
            { id: 2, courseId: 1, title: "Unit 2", description: "Learn more about Stocks", order: 2 },
            { id: 3, courseId: 2, title: "Unit 1", description: "Learn the basics of Budgeting", order: 3 },
            { id: 4, courseId: 2, title: "Unit 2", description: "Learn more about Budgeting", order: 4 },
            { id: 5, courseId: 3, title: "Unit 1", description: "Learn the basics of Loans", order: 5 },
            { id: 6, courseId: 3, title: "Unit 2", description: "Learn more about Loans", order: 6 },
            { id: 7, courseId: 4, title: "Unit 1", description: "Learn the basics of investment", order: 7 },
            { id: 8, courseId: 4, title: "Unit 2", description: "Learn more about investment", order: 8 },
            { id: 9, courseId: 5, title: "Unit 1", description: "Learn the basics of banking", order: 9 },
            { id: 10, courseId: 5, title: "Unit 2", description: "Learn more about banking", order: 10 },
            { id: 11, courseId: 6, title: "Unit 1", description: "Learn the basics of finance", order: 11 },
            { id: 12, courseId: 6, title: "Unit 2", description: "Learn more about finance", order: 12 },
            { id: 13, courseId: 7, title: "Unit 1", description: "Learn the basics of insurance", order: 13 },
            { id: 14, courseId: 7, title: "Unit 2", description: "Learn more about insurance", order: 14 },
            { id: 15, courseId: 8, title: "Unit 1", description: "Learn the basics of retirement planning", order: 15 },
            { id: 16, courseId: 8, title: "Unit 2", description: "Learn more about retirement planning", order: 16 },
            { id: 17, courseId: 9, title: "Daily Challenge", description: "Unlocks each challenge everyday", order: 17}
        ]);

        //lessons
        await db.insert(schema.lessons).values([
                { id: 1, unitId: 1, order: 1, title: "STOCKS" },
                { id: 2, unitId: 1, order: 2, title: "STOCKS" },
                { id: 3, unitId: 1, order: 3, title: "STOCKS" },
                { id: 4, unitId: 1, order: 4, title: "STOCKS" },
                { id: 5, unitId: 1, order: 5, title: "STOCKS" },
                { id: 6, unitId: 1, order: 6, title: "STOCKS" },
                { id: 7, unitId: 2, order: 7, title: "STOCKS" },
                { id: 8, unitId: 2, order: 8, title: "STOCKS" },
                { id: 9, unitId: 2, order: 9, title: "STOCKS" },
                { id: 10, unitId: 2, order: 10, title: "STOCKS" },
                { id: 11, unitId: 2, order: 11, title: "STOCKS" },
                { id: 12, unitId: 2, order: 12, title: "STOCKS" },
                { id: 13, unitId: 3, order: 13, title: "BUDGETING" },
                { id: 14, unitId: 3, order: 14, title: "BUDGETING" },
                { id: 15, unitId: 3, order: 15, title: "BUDGETING" },
                { id: 16, unitId: 3, order: 16, title: "BUDGETING" },
                { id: 17, unitId: 3, order: 17, title: "BUDGETING" },
                { id: 18, unitId: 3, order: 18, title: "BUDGETING" },
                { id: 19, unitId: 5, order: 19, title: "LOANS" },
                { id: 20, unitId: 5, order: 20, title: "LOANS" },
                { id: 21, unitId: 5, order: 21, title: "LOANS" },
                { id: 22, unitId: 5, order: 22, title: "LOANS" },
                { id: 23, unitId: 5, order: 23, title: "LOANS" },
                { id: 24, unitId: 5, order: 24, title: "LOANS" },
                { id: 25, unitId: 7, order: 25, title: "INVESTMENT" },
                { id: 26, unitId: 7, order: 26, title: "INVESTMENT" },
                { id: 27, unitId: 7, order: 27, title: "INVESTMENT" },
                { id: 28, unitId: 7, order: 28, title: "INVESTMENT" },
                { id: 29, unitId: 7, order: 29, title: "INVESTMENT" },
                { id: 30, unitId: 7, order: 30, title: "INVESTMENT" },
                { id: 31, unitId: 9, order: 31, title: "BANK" },
                { id: 32, unitId: 9, order: 32, title: "BANK" },
                { id: 33, unitId: 9, order: 33, title: "BANK" },
                { id: 34, unitId: 9, order: 34, title: "BANK" },
                { id: 35, unitId: 9, order: 35, title: "BANK" },
                { id: 36, unitId: 11, order: 36, title: "FINANCE" },
                { id: 37, unitId: 11, order: 37, title: "FINANCE" },
                { id: 38, unitId: 11, order: 38, title: "FINANCE" },
                { id: 39, unitId: 11, order: 39, title: "FINANCE" },
                { id: 40, unitId: 11, order: 41, title: "FINANCE" },
                { id: 41, unitId: 11, order: 41, title: "FINANCE" },
                { id: 42, unitId: 13, order: 42, title: "INSURANCE" },
                { id: 43, unitId: 13, order: 43, title: "INSURANCE" },
                { id: 44, unitId: 13, order: 44, title: "INSURANCE" },
                { id: 45, unitId: 13, order: 45, title: "INSURANCE" },
                { id: 46, unitId: 13, order: 46, title: "INSURANCE" },
                { id: 47, unitId: 13, order: 47, title: "INSURANCE" },
                { id: 48, unitId: 15, order: 48, title: "RETIREMNT" },
                { id: 49, unitId: 15, order: 49, title: "RETIREMNT" },
                { id: 50, unitId: 15, order: 50, title: "RETIREMNT" },
                { id: 51, unitId: 15, order: 51, title: "RETIREMNT" },
                { id: 52, unitId: 15, order: 52, title: "RETIREMNT" },
                { id: 53, unitId: 15, order: 53, title: "RETIREMNT" },
                { id: 54, unitId: 17, order: 54, title: "CHALLENGE" },
                { id: 55, unitId: 17, order: 55, title: "CHALLENGE" },
                { id: 56, unitId: 17, order: 56, title: "CHALLENGE" },
                { id: 57, unitId: 17, order: 57, title: "CHALLENGE" },
                { id: 58, unitId: 17, order: 58, title: "CHALLENGE" },
                { id: 59, unitId: 17, order: 59, title: "CHALLENGE" },
                { id: 60, unitId: 17, order: 60, title: "CHALLENGE" },
                
        ]);

        //challenges
        await db.insert(schema.challenges).values([
                {id: 1, lessonId: 1, type: "ASSIST", order: 1, question: "What are Stocks? A stock represents ownership in a company and a claim on part of the company’s assets and earnings. When you own stock in a company, you own shares of that company, making you a shareholder. Stocks can be bought and sold on stock exchanges, and their value can fluctuate based on company performance and market conditions.",},
                { id: 2, lessonId: 1, type: "SELECT", order: 2, question: "What are Stocks?" },
                {id: 3, lessonId: 2, type: "VIDEO", order: 3, videoSrc: "/stocksIntro.mp4"},
                {id: 4, lessonId: 2, type: "SELECT", order: 4, question: "What do you receive when you buy a stock?"},
                {id: 5, lessonId: 3, type: "ASSIST", order: 5, question: "What are Stocks? A stock represents ownership in a company and a claim on part of the company’s assets and earnings. When you own stock in a company, you own shares of that company, making you a shareholder. Stocks can be bought and sold on stock exchanges, and their value can fluctuate based on company performance and market conditions.",},
                { id: 6, lessonId: 3, type: "SELECT", order: 6, question: "What are Stocks?" },
                {id: 7, lessonId: 4, type: "VIDEO", order: 7, videoSrc: "/stocksIntro.mp4"},
                {id: 8, lessonId: 4, type: "SELECT", order: 8, question: "What do you receive when you buy a stock?"},
                {id: 9, lessonId: 13, type: "ASSIST", order: 9, question: "What is Budget? A budget is a plan that helps you manage your money. It shows you how much money you have, how much money you need to spend on different things, and how much money you can save or use for other goals. A budget can help you make smart decisions with your money and avoid problems like overspending, debt, or running out of money."},
                {id: 10,lessonId: 13, type: "SELECT", order: 10, question:"What is the main purpose of a budget?"},
                {id: 11, lessonId: 14, type: "VIDEO", order: 11, videoSrc: "/budget.mp4"},
                {id: 12, lessonId: 14, type: "SELECT", order: 12, question: "What are expenses?"},
                {id: 13, lessonId: 19, type: "ASSIST",order: 13, question: "Sometimes, you may want to buy something you can't afford right now, like a laptop, bike, or trip, or you might have an unexpected expense like a car repair or medical bill. Instead of waiting to save up, you can borrow money from family, friends, or a financial institution. This is called taking out a loan or using credit. When you borrow money, you have to pay it back later with extra money added, called interest and fees."},
                {id: 14, lessonId: 19, type: "ASSIST", order: 14, question: "What is Interest? Interest is the amount of money that you pay to the lender for using their money. It is usually expressed as a percentage of the amount you borrow, and it is charged over a period of time, such as a month, a year, or the entire term of the loan."},
                {id: 15, lessonId: 19, type: "SELECT", order: 15, question: "What is Interest?"},
                {id: 16, lessonId: 25, type: "VIDEO", order: 16, videoSrc: "/investment.mp4"},
                {id: 17, lessonId: 25, type: "ASSIST", order: 17, question: "What is Investment? Investing involves putting money into assets like real estate, stocks, bonds, and mutual funds, with the expectation that their value will grow over time. This growth can help you achieve long-term goals such as home ownership or retirement."},
                {id: 18, lessonId: 25, type: "SELECT",order: 18, question: "Which of the following is a primary goal of investing?"},
                {id: 19, lessonId: 26, type: "ASSIST", order: 19, question: "Saving & Investing Saving involves putting money into secure accounts like bank savings or CDs, offering liquidity and modest interest. Investing allocates funds into assets like stocks, bonds, or mutual funds for higher long-term returns, despite varying risks and value fluctuations. Choosing between saving and investing hinges on goals, risk tolerance, and financial timeline, ensuring an effective strategy for wealth growth and protection."},
                {id: 20, lessonId: 26, type: "ASSIST", order: 20, question: "How saving and investing can work together? Saving and investing can complement each other in helping you achieve your financial goals. For example, you might save money for emergencies and short-term goals, while investing for long-term goals like retirement. By having both savings and investments, you can ensure that you have money available for immediate needs and also have your money growing for the future."},
                {id: 21, lessonId: 26, type: "SELECT", order: 21, question: "What is the primary difference between saving and investing?"},
                {id: 22 ,lessonId: 31, type: "VIDEO", order: 22, videoSrc: "/bank.mp4"},
                {id: 23, lessonId: 31, type: "ASSIST", order: 23, question: "Banks are important financial institutions that help people and businesses manage their money. They offer safe places to store money, provide loans and credit, and charge interest on borrowed funds. Banks also give financial advice, help with investments, and handle foreign exchange. Regulated by central authorities, banks ensure the safety of deposits and support economic stability. Overall, they help with financial transactions and promote financial well-being."},
                {id: 24, lessonId: 31, type: "SELECT", order: 24, question: "What is the primary role of banks in the economy?"},
                {id: 25, lessonId: 32, type: "ASSIST",order: 25 ,question: "A bank's income statement shows how well it has performed financially over a specific period, like a quarter or year. It lists the money the bank earned from interest on loans, service fees, and investments, then subtracts operating costs like salaries and rent to find the operating income. After accounting for other gains or losses and taxes, it calculates the net income or profit. This statement helps understand the bank's profitability and efficiency."},
                {id: 26, lessonId: 32, type: "ASSIST", order: 26, question: "Bank notes & Cheque Bank notes are physical currency issued by central banks, used as legal tender. Checks are written orders to a bank to transfer funds from an account to a recipient. Both facilitate transactions and support economic activities."},
                {id: 27, lessonId: 32, type: "SELECT", order: 27, question: "What is the primary function of bank notes in financial transactions?"},
                {id: 28 ,lessonId: 36, type: "VIDEO", order: 28, videoSrc: "/finance.mp4"},
                {id: 29, lessonId: 36, type: "ASSIST", order: 29, question: "Understanding your money personality means knowing your attitudes and habits towards money. There are four main types: savers, spenders, balancers, and investors. Savers are careful with spending and good at saving but may avoid risks that could lead to growth. Each type has unique strengths and weaknesses that affect financial decisions. Knowing your money personality can help you improve your financial strategies and achieve your goals."},
                {id: 30, lessonId: 36, type: "SELECT", order: 30, question: "Which money personality type is likely to excel in budgeting and prioritize saving, but may avoid taking risks?"},
                {id: 31, lessonId: 37, type: "ASSIST", order: 31, question: "To determine your money personality, consider if you tend to save money or spend it quickly. Savers focus on long-term goals and saving, while spenders enjoy buying things and may not save as much. There are also investors, who seek growth opportunities, and balanced personalities, who mix saving and spending. Your money personality influences how you manage your finances."},
                {id: 32, lessonId: 37, type: "SELECT", order: 32, question: "Balancers are individuals who only focus on saving money and avoid spending or investing."},
                {id: 33, lessonId: 37, type: "SELECT", order: 33, question: "What strategy is suggested for spenders to avoid overspending?"},
                {id: 34 ,lessonId: 42, type: "VIDEO", order: 34, videoSrc: "/insurance.mp4"},
                {id: 35, lessonId: 42, type: "ASSIST", order: 35, question: "What is insurance?Insurance is a type of contract that transfers the risk of something bad happening to an insurance company. In exchange for paying a fee or premium, the insurance company promises to help cover the costs of the unexpected event."},
                {id: 36, lessonId: 42, type: "SELECT", order: 36, question: "What is the primary purpose of insurance?"},
                {id: 37, lessonId: 43, type: "ASSIST", order: 37, question: "How does insurance work? Insurance spreads the risk of financial loss among many people, which is called pooling risk. When a group of people buys insurance, not everyone will face a problem at the same time. The insurance company uses the premiums paid by everyone to cover the losses of those who do experience issues, providing protection against unexpected events for all."},
                {id: 38, lessonId: 43, type: "ASSIST", order: 38, question: "Insurance Terminology:- Premium: The fee you pay for insurance coverage.;Deductible: The amount you must pay before the insurance company covers a claim.;Copay: A fixed payment you make for covered services.;Policy Limit: The maximum amount the insurance company will pay for a claim.;Claim: A request for payment to cover a loss.;Benefit: The money the insurance company agrees to pay for an approved claim."},
                {id: 39, lessonId: 43, type: "SELECT", order: 39, question: "How does insurance work to reduce financial risk?"},
                {id: 40 ,lessonId: 48, type: "VIDEO", order: 40, videoSrc: "/retirement.mp4"},
                {id: 41, lessonId: 48, type: "ASSIST", order: 41, question: "Planning for retirement is important because people are spending as many years retired as they were working. When you retire, your regular paycheck stops, and you need to cover your daily expenses for many years. Social Security provides only a small amount and starts later in life, making it hard to live on alone. To retire early or live comfortably, you should start planning and saving now."},
                {id: 42, lessonId: 48, type: "SELECT", order: 42, question: "Why is it important to plan for retirement?"},
                {id: 43, lessonId: 49, type: "ASSIST", order: 43, question: "When planning for retirement, consider essential expenses like housing, food, transportation, healthcare, entertainment, and insurance/taxes. Use methods like budgeting, the replacement ratio, and online calculators to estimate these costs. To reduce expenses and increase income, consider downsizing, relocating, working part-time, or delaying retirement. Start planning and saving early to ensure a comfortable retirement."},
                {id: 44, lessonId: 49, type: "SELECT", order: 44, question: "Retirement expenses typically decrease as you age and become more settled in your retirement lifestyle."},
                {id: 45, lessonId: 49, type: "SELECT", order: 45, question: "What is a benefit of planning for retirement?"},
                {id: 46, lessonId: 54, type: "ASSIST", order: 46, question: "Situation: You have just started your first job and need to create a budget to manage your expenses. How would you go about creating a budget, and what factors would you consider to ensure you're saving enough money each month? Question: What are the key components of a personal budget, and how can you ensure you stick to it?"},
        ]);

        // challenge options
        await db.insert(schema.challengeOptions).values([
                { id: 1, challengeId: 1, correct: false, text: "Read Aloud", audioSrc: "/whatAreStocks.mp3" },
                { id: 2, challengeId: 1, correct: true, text: "Got it" },
                { id: 3, challengeId: 2, correct: false, text: "Stocks are loans given to companies by investors" },
                { id: 4, challengeId: 2, correct: false, text: "Stocks are government-issued bonds" },
                {id: 5, challengeId: 2, correct: true, text: "Stocks represent ownership in a company and a claim on part of its assets and earnings."},
                {id: 6, challengeId: 2, correct: false, text: "Stocks are fixed-income investments"},
                {id: 7, challengeId: 3, correct: false, text: "Didn't get it"},
                {id: 8, challengeId: 3, correct: true, text: "Got it"},
                {id: 9, challengeId: 4, correct: false, text: "A guarantee fixed income"},
                {id: 10, challengeId: 4, correct: true,  text: "Ownership in a company and a claim on part of its assets and earnings"},
                {id: 11, challengeId: 4, correct: false, text: "A loan to the company"},
                {id: 12, challengeId: 4, correct: false, text: "A government bond"},
                { id: 13, challengeId: 5, correct: false, text: "Read Aloud", audioSrc: "/whatAreStocks.mp3" },
                { id: 14, challengeId: 5, correct: true, text: "Got it" },
                { id: 15, challengeId: 6, correct: false, text: "Stocks are loans given to companies by investors" },
                { id: 16, challengeId: 6, correct: false, text: "Stocks are government-issued bonds" },
                {id: 17, challengeId: 6, correct: true, text: "Stocks represent ownership in a company and a claim on part of its assets and earnings."},
                {id: 18, challengeId: 6, correct: false, text: "Stocks are fixed-income investments"},
                {id: 19, challengeId: 7, correct: false, text: "Didn't get it"},
                {id: 20, challengeId: 7, correct: true, text: "Got it"},
                {id: 21, challengeId: 8, correct: false, text: "A guarantee fixed income"},
                {id: 22, challengeId: 8, correct: true,  text: "Ownership in a company and a claim on part of its assets and earnings"},
                {id: 23, challengeId: 8, correct: false, text: "A loan to the company"},
                {id: 24, challengeId: 8, correct: false, text: "A government bond"},
                {id: 25, challengeId: 9, correct: false, text: "Read Aloud", audioSrc: "/budget.mp3" },
                {id: 26, challengeId: 9, correct: true, text: "Got it"},
                {id: 27, challengeId: 10, correct: false, text: "To show you how much debt you can accumulate"},
                {id: 28, challengeId: 10, correct: true, text: "To help you manage your money by showing income, expenses, and savings" },
                {id: 29, challengeId: 10, correct: false, text: "To determine how much money you can borrow"},
                {id: 30, challengeId: 10, correct: false, text: "To track your spending without any financial planning"},
                {id: 31, challengeId: 11, correct: false, text: "Didn't get it"},
                {id: 32, challengeId: 11, correct: true, text: "Got it"},
                {id: 33, challengeId: 12, correct: false, text: "Money you save for future goals"},
                {id: 34, challengeId: 12, correct: false, text: "Money you earn from a job"},
                {id: 35, challengeId: 12, correct: true, text: "Money you spend on things like bills, food, and entertainment"},
                {id: 36, challengeId: 12, correct: false, text: "Money you receive as a gift"},
                {id: 37, challengeId: 13, correct: false, text: "Read Aloud", audioSrc: "/loans.mp3"},
                {id: 38, challengeId: 13, correct: true, text: "Got it"},
                {id: 39 , challengeId: 14, correct: false, text: "Read Aloud", audioSrc: "/interest.mp3"},
                {id: 40, challengeId: 14, correct: true, text: "Got it"},
                {id: 41, challengeId: 15, correct: false, text: "The amount of money you receive for saving money"},
                {id: 42, challengeId: 15, correct: true, text: "The amount of money you pay to the lender for using their money, usually expressed as a percentage of the amount borrowed"},
                {id: 43, challengeId: 15, correct: false, text: "The total amount of the loan you borrow"},
                {id: 44, challengeId: 15, correct: false, text: "A fee charged for early repayment of a loan"},
                {id: 45, challengeId: 17, correct: false, text: "Read Aloud", audioSrc: "/inv1.mp3"},
                {id:46, challengeId: 17, correct: true, text: "Got It"},
                {id: 47, challengeId: 16, correct: false, text: "Didn't get it"},
                {id: 48, challengeId: 16, correct: true, text: "Got it"},
                {id: 49 ,challengeId: 18, correct: false, text: "Keeping money in safe, accessible accounts for immediate use."},
                {id: 50 ,challengeId: 18, correct: true, text: "Putting money into assets with the expectation that their value will grow over time."},
                {id: 51 ,challengeId: 18, correct: false, text: "Storing money in a way that ensures it remains the same amount."},
                {id: 52 ,challengeId: 18, correct: false, text: "Avoiding any risk and ensuring 100% capital preservation."},
                {id: 53, challengeId: 19, correct: false, text: "Read aloud", audioSrc: "/inv2.mp3"},
                {id: 54, challengeId: 19, correct: true ,text: "Got it"},
                {id: 55, challengeId: 20, correct: false, text: "Read aloud", audioSrc: "/inv3.mp3"},
                {id: 56, challengeId: 20, correct: true, text: "Got it"},
                {id: 57, challengeId: 21, correct: false, text: "Savings accounts offer higher returns compared to investments."},
                {id: 58, challengeId: 21, correct: true, text: "Saving involves keeping money in secure accounts with easy access, while investing involves putting money into assets with the goal of higher returns over time."},
                {id: 59, challengeId: 21, correct: false, text: "Investing ensures 100% capital preservation, whereas saving involves some degree of risk."},
                {id: 60, challengeId: 21, correct: false, text: "Savings are typically for short-term goals, while investments are for long-term financial planning."},
                {id: 61, challengeId: 22, correct: false ,text: "Didn't get it"},
                {id: 62, challengeId: 22, correct: true, text: "Got it"},
                {id: 63, challengeId: 23, correct: false, text: "Read Aloud", audioSrc: "/bank1.mp3"},
                {id: 64, challengeId: 23, correct: true, text: "Got it"},
                {id: 65, challengeId: 24, correct: false, text: "Promoting environmental sustainability initiatives."},
                {id: 66, challengeId: 24, correct: false, text: "Regulating government policies on taxation."},
                {id: 67, challengeId: 24, correct: true, text: "Offering deposit accounts and loans to individuals and businesses."},
                {id: 68, challengeId: 24, correct: false, text: "Providing entertainment services to customers."},
                {id: 69, challengeId: 25, correct: false, text: "Read Aloud", audioSrc: "/bank2.mp3"},
                {id: 70, challengeId: 25, correct: true, text: "Got it"},
                {id: 71, challengeId: 26, correct: false, text: "Read Aloud", audioSrc: "/bank3.mp3"},
                {id: 72, challengeId: 26, correct: true, text: "Got it"},
                {id: 73, challengeId: 27, correct: false, text: "Acting as digital currency."},
                {id: 74, challengeId: 27, correct: false, text: "Providing investment opportunities."},
                {id: 75, challengeId: 27, correct: true, text: "Serving as legal tender."},
                {id: 76, challengeId: 27, correct: false, text: "Facilitating online payments."},
                {id: 77, challengeId: 28, correct: false ,text: "Didn't get it"},
                {id: 78, challengeId: 28, correct: true, text: "Got it"},
                {id: 79, challengeId: 29, correct: false, text: "Read Aloud", audioSrc: "/fin1.mp3"},
                {id: 80, challengeId: 29, correct: true, text: "Got it"},
                {id: 81, challengeId: 30, correct: false, text: "Spender"},
                {id: 82, challengeId: 30, correct: false, text: "Balancer"},
                {id: 83, challengeId: 30, correct: false, text: "Investor"},
                {id: 84, challengeId: 30, correct: true, text: "Saver"},
                {id: 85, challengeId: 31, correct: false, text: "Read Aloud", audioSrc: "/fin2.mp3"},
                {id: 86, challengeId: 31, correct: true, text: "Got it"},
                {id: 87, challengeId: 32, correct: false, text: "False"},
                {id: 88, challengeId: 32, correct: true, text: "True"},
                {id: 89, challengeId: 33, correct: true, text: "Set aside a portion of income for savings or investments before spending"},
                {id: 90, challengeId: 33, correct: false, text: "Use credit cards for every purchase"},
                {id: 91, challengeId: 33, correct: false, text: "Avoid setting any spending limits"},
                {id: 92, challengeId: 33, correct: false, text: "Rely on impulse buying for all purchases"},
                {id: 93, challengeId: 34, correct: false ,text: "Didn't get it"},
                {id: 94, challengeId: 34, correct: true, text: "Got it"},
                {id: 95, challengeId: 35, correct: false, text: "Read Aloud", audioSrc: "/insurance1.mp3"},
                {id: 96, challengeId: 35, correct: true, text: "Got it"},
                {id: 97, challengeId: 36, correct: false, text: "To invest your money for long-term growth."},
                {id: 98, challengeId: 36, correct: false, text: "To provide a fixed income stream during retirement"},
                {id: 99, challengeId: 36, correct: false, text: "To offer tax benefits on your yearly earnings."},
                {id: 100, challengeId: 36, correct: true, text: "To guarantee financial protection against unexpected events"},
                {id: 101, challengeId: 37, correct: false, text: "Read Aloud", audioSrc: "/insurance2.mp3"},
                {id: 102, challengeId: 37, correct: true, text: "Got it"},
                {id: 103, challengeId: 38, correct: false, text: "Read Aloud", audioSrc: "/insurance3.mp3"},
                {id: 104, challengeId: 38, correct: true, text: "Got it"},
                {id: 105, challengeId: 39, correct: false, text: "By offering discounts on repairs and replacements"},
                {id: 106, challengeId: 39, correct: false, text: "By providing legal representation in case of accidents."},
                {id: 107, challengeId: 39, correct: true, text: "By spreading the cost of potential losses among a large group."},
                {id: 108, challengeId: 39, correct: false, text: "By guaranteeing a specific amount of money in case of an event."},
                {id: 109, challengeId: 40, correct: false ,text: "Didn't get it"},
                {id: 110, challengeId: 40, correct: true, text: "Got it"},
                {id: 111, challengeId: 41, correct: false, text: "Read Aloud", audioSrc: "/ret1.mp3"},
                {id: 112, challengeId: 41, correct: true, text: "Got it"},
                {id: 113, challengeId: 42, correct: true, text: "To ensure you have enough income to cover your expenses after you stop working."},
                {id: 114, challengeId: 42, correct: false, text: "To invest your money for long-term growth"},
                {id: 115, challengeId: 42, correct: true, text: "To pay off all your debts before you retire."},
                {id: 116, challengeId: 42, correct: false, text: "To travel the world extensively during your golden years."},
                {id: 117, challengeId: 43, correct: false, text: "Read Aloud", audioSrc: "/ret2.mp3"},
                {id: 118, challengeId: 43, correct: true, text: "Got it"},
                {id: 119, challengeId: 44, correct: false, text: "True"},
                {id: 120, challengeId: 44, correct: true, text: "False"},
                {id: 121, challengeId: 45, correct: true, text: "Having the peace of mind of knowing your future expenses are covered."},
                {id: 122, challengeId: 45, correct: false, text: "Avoiding work altogether after you retire."},
                {id: 123, challengeId: 45, correct: true, text: "Needing to rely on your children for financial support."},
                {id: 124, challengeId: 45, correct: false, text: "Experiencing a higher level of stress during your working years."},
                {id: 125, challengeId: 46, correct: true, text: "Track your monthly income and expenses, and allocate specific amounts for different categories such as housing, food, transportation, and savings"},
                {id: 126, challengeId: 46, correct: false, text: "Spend freely and check your account balance occasionally to make sure you don’t run out of money"},


        ]);

       

        console.log("Seeding Finished");
    } catch (error) {
        console.error("Failed to seed the database", error);
    }
};

main();