import "dotenv/config";
import { drizzle } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";

import * as schema from "../db/schema";
import { Flag } from "lucide-react";
import { truncate } from "fs/promises";

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql, { schema });

const main = async () => {
    try {
        console.log("Seeding Database");

        // Clear existing data
        await db.delete(schema.courses);
        await db.delete(schema.units);
        await db.delete(schema.lessons);
        await db.delete(schema.challenges);
        await db.delete(schema.challengeOptions);
        await db.delete(schema.challengeProgress);

        // Insert courses
        await db.insert(schema.courses).values([
            { id: 1, title: "Stocks", imageSrc: "/stock.png" },
            { id: 2, title: "Budgeting", imageSrc: "/budget.png" },
            { id: 3, title: "Loans & Debts", imageSrc: "/loan.png" },
            { id: 4, title: "Investment", imageSrc: "/investment.png" },
            { id: 5, title: "Bank", imageSrc: "/bank.png" },
            { id: 6, title: "Financial Goals", imageSrc: "/finance.png" },
            { id: 7, title: "Insurance", imageSrc: "/insurance.png" },
            { id: 8, title: "Retirement", imageSrc: "/retirement.png" },
            {id: 9, title: "Challenges", imageSrc: "/challenge.png"}
        ]);

        //units
        await db.insert(schema.units).values([
            { id: 1, courseId: 1, title: "Unit 1", description: "Learn the basics of Stocks", order: 1 },
            { id: 2, courseId: 1, title: "Unit 2", description: "Learn more about Stocks", order: 2 },
            { id: 3, courseId: 2, title: "Unit 1", description: "Learn the basics of Budgeting", order: 3 },
            { id: 4, courseId: 2, title: "Unit 2", description: "Learn more about Budgeting", order: 4 },
            { id: 5, courseId: 3, title: "Unit 1", description: "Learn the basics of Loans", order: 5 },
            { id: 6, courseId: 3, title: "Unit 2", description: "Learn more about Loans", order: 6 },
            { id: 7, courseId: 4, title: "Unit 1", description: "Learn the basics of investment", order: 7 },
            { id: 8, courseId: 4, title: "Unit 2", description: "Learn more about investment", order: 8 },
            { id: 9, courseId: 5, title: "Unit 1", description: "Learn the basics of banking", order: 9 },
            { id: 10, courseId: 5, title: "Unit 2", description: "Learn more about banking", order: 10 },
            { id: 11, courseId: 6, title: "Unit 1", description: "Learn the basics of finance", order: 11 },
            { id: 12, courseId: 6, title: "Unit 2", description: "Learn more about finance", order: 12 },
            { id: 13, courseId: 7, title: "Unit 1", description: "Learn the basics of insurance", order: 13 },
            { id: 14, courseId: 7, title: "Unit 2", description: "Learn more about insurance", order: 14 },
            { id: 15, courseId: 8, title: "Unit 1", description: "Learn the basics of retirement planning", order: 15 },
            { id: 16, courseId: 8, title: "Unit 2", description: "Learn more about retirement planning", order: 16 },
            { id: 17, courseId: 9, title: "Daily Challenge", description: "Unlocks each challenge everyday", order: 17}
        ]);

        //lessons
        await db.insert(schema.lessons).values([
                { id: 1, unitId: 1, order: 1, title: "STOCKS" },
                { id: 2, unitId: 1, order: 2, title: "STOCKS" },
                { id: 3, unitId: 1, order: 3, title: "STOCKS" },
                { id: 4, unitId: 1, order: 4, title: "STOCKS" },
                { id: 5, unitId: 1, order: 5, title: "STOCKS" },
                { id: 6, unitId: 1, order: 6, title: "STOCKS" },
                { id: 7, unitId: 2, order: 7, title: "STOCKS" },
                { id: 8, unitId: 2, order: 8, title: "STOCKS" },
                { id: 9, unitId: 2, order: 9, title: "STOCKS" },
                { id: 10, unitId: 2, order: 10, title: "STOCKS" },
                { id: 11, unitId: 2, order: 11, title: "STOCKS" },
                { id: 12, unitId: 2, order: 12, title: "STOCKS" },
                { id: 13, unitId: 3, order: 13, title: "BUDGETING" },
                { id: 14, unitId: 3, order: 14, title: "BUDGETING" },
                { id: 15, unitId: 3, order: 15, title: "BUDGETING" },
                { id: 16, unitId: 3, order: 16, title: "BUDGETING" },
                { id: 17, unitId: 3, order: 17, title: "BUDGETING" },
                { id: 18, unitId: 3, order: 18, title: "BUDGETING" },
                { id: 19, unitId: 5, order: 19, title: "LOANS" },
                { id: 20, unitId: 5, order: 20, title: "LOANS" },
                { id: 21, unitId: 5, order: 21, title: "LOANS" },
                { id: 22, unitId: 5, order: 22, title: "LOANS" },
                { id: 23, unitId: 5, order: 23, title: "LOANS" },
                { id: 24, unitId: 5, order: 24, title: "LOANS" },
                { id: 25, unitId: 7, order: 25, title: "INVESTMENT" },
                { id: 26, unitId: 7, order: 26, title: "INVESTMENT" },
                { id: 27, unitId: 7, order: 27, title: "INVESTMENT" },
                { id: 28, unitId: 7, order: 28, title: "INVESTMENT" },
                { id: 29, unitId: 7, order: 29, title: "INVESTMENT" },
                { id: 30, unitId: 7, order: 30, title: "INVESTMENT" },
                { id: 31, unitId: 9, order: 31, title: "BANK" },
                { id: 32, unitId: 9, order: 32, title: "BANK" },
                { id: 33, unitId: 9, order: 33, title: "BANK" },
                { id: 34, unitId: 9, order: 34, title: "BANK" },
                { id: 35, unitId: 9, order: 35, title: "BANK" },
                { id: 36, unitId: 11, order: 36, title: "FINANCE" },
                { id: 37, unitId: 11, order: 37, title: "FINANCE" },
                { id: 38, unitId: 11, order: 38, title: "FINANCE" },
                { id: 39, unitId: 11, order: 39, title: "FINANCE" },
                { id: 40, unitId: 11, order: 41, title: "FINANCE" },
                { id: 41, unitId: 11, order: 41, title: "FINANCE" },
                { id: 42, unitId: 13, order: 42, title: "INSURANCE" },
                { id: 43, unitId: 13, order: 43, title: "INSURANCE" },
                { id: 44, unitId: 13, order: 44, title: "INSURANCE" },
                { id: 45, unitId: 13, order: 45, title: "INSURANCE" },
                { id: 46, unitId: 13, order: 46, title: "INSURANCE" },
                { id: 47, unitId: 13, order: 47, title: "INSURANCE" },
                { id: 48, unitId: 15, order: 48, title: "RETIREMNT" },
                { id: 49, unitId: 15, order: 49, title: "RETIREMNT" },
                { id: 50, unitId: 15, order: 50, title: "RETIREMNT" },
                { id: 51, unitId: 15, order: 51, title: "RETIREMNT" },
                { id: 52, unitId: 15, order: 52, title: "RETIREMNT" },
                { id: 53, unitId: 15, order: 53, title: "RETIREMNT" },
                { id: 54, unitId: 17, order: 54, title: "CHALLENGE" },
                { id: 55, unitId: 17, order: 55, title: "CHALLENGE" },
                { id: 56, unitId: 17, order: 56, title: "CHALLENGE" },
                { id: 57, unitId: 17, order: 57, title: "CHALLENGE" },
                { id: 58, unitId: 17, order: 58, title: "CHALLENGE" },
                { id: 59, unitId: 17, order: 59, title: "CHALLENGE" },
                { id: 60, unitId: 17, order: 60, title: "CHALLENGE" },
                
        ]);

        //challenges
        await db.insert(schema.challenges).values([
                {id: 1, lessonId: 1, type: "ASSIST", order: 1, question: "What are Stocks? A stock represents ownership in a company and a claim on part of the company’s assets and earnings. When you own stock in a company, you own shares of that company, making you a shareholder. Stocks can be bought and sold on stock exchanges, and their value can fluctuate based on company performance and market conditions.",},
                { id: 2, lessonId: 1, type: "SELECT", order: 2, question: "What are Stocks?" },
                {id: 3, lessonId: 2, type: "VIDEO", order: 3, videoSrc: "/stocksIntro.mp4"},
                {id: 4, lessonId: 2, type: "SELECT", order: 4, question: "What do you receive when you buy a stock?"},
                {id: 5, lessonId: 3, type: "ASSIST", order: 5, question: "What are Stocks? A stock represents ownership in a company and a claim on part of the company’s assets and earnings. When you own stock in a company, you own shares of that company, making you a shareholder. Stocks can be bought and sold on stock exchanges, and their value can fluctuate based on company performance and market conditions.",},
                { id: 6, lessonId: 3, type: "SELECT", order: 6, question: "What are Stocks?" },
                {id: 7, lessonId: 4, type: "VIDEO", order: 7, videoSrc: "/stocksIntro.mp4"},
                {id: 8, lessonId: 4, type: "SELECT", order: 8, question: "What do you receive when you buy a stock?"},
                {id: 9, lessonId: 13, type: "ASSIST", order: 9, question: "What is Budget? A budget is a plan that helps you manage your money. It shows you how much money you have, how much money you need to spend on different things, and how much money you can save or use for other goals. A budget can help you make smart decisions with your money and avoid problems like overspending, debt, or running out of money."},
                {id: 10,lessonId: 13, type: "SELECT", order: 10, question:"What is the main purpose of a budget?"},
                {id: 11, lessonId: 14, type: "VIDEO", order: 11, videoSrc: "/budget.mp4"},
                {id: 12, lessonId: 14, type: "SELECT", order: 12, question: "What are expenses?"},
                {id: 13, lessonId: 19, type: "ASSIST",order: 13, question: "Sometimes, you may want to buy something you can't afford right now, like a laptop, bike, or trip, or you might have an unexpected expense like a car repair or medical bill. Instead of waiting to save up, you can borrow money from family, friends, or a financial institution. This is called taking out a loan or using credit. When you borrow money, you have to pay it back later with extra money added, called interest and fees."},
                {id: 14, lessonId: 19, type: "ASSIST", order: 14, question: "What is Interest? Interest is the amount of money that you pay to the lender for using their money. It is usually expressed as a percentage of the amount you borrow, and it is charged over a period of time, such as a month, a year, or the entire term of the loan."},
                {id: 15, lessonId: 19, type: "SELECT", order: 15, question: "What is Interest?"},
                {id: 16, lessonId: 25, type: "VIDEO", order: 16, videoSrc: "/investment.mp4"},
                {id: 17, lessonId: 25, type: "ASSIST", order: 17, question: "What is Investment? Investing involves putting money into assets like real estate, stocks, bonds, and mutual funds, with the expectation that their value will grow over time. This growth can help you achieve long-term goals such as home ownership or retirement."},
                {id: 18, lessonId: 25, type: "SELECT",order: 18, question: "Which of the following is a primary goal of investing?"},
                {id: 19, lessonId: 26, type: "ASSIST", order: 19, question: "Saving & Investing Saving involves putting money into secure accounts like bank savings or CDs, offering liquidity and modest interest. Investing allocates funds into assets like stocks, bonds, or mutual funds for higher long-term returns, despite varying risks and value fluctuations. Choosing between saving and investing hinges on goals, risk tolerance, and financial timeline, ensuring an effective strategy for wealth growth and protection."},
                {id: 20, lessonId: 26, type: "ASSIST", order: 20, question: "How saving and investing can work together? Saving and investing can complement each other in helping you achieve your financial goals. For example, you might save money for emergencies and short-term goals, while investing for long-term goals like retirement. By having both savings and investments, you can ensure that you have money available for immediate needs and also have your money growing for the future."},
                {id: 21, lessonId: 26, type: "SELECT", order: 21, question: "What is the primary difference between saving and investing?"},
                {id: 22 ,lessonId: 31, type: "VIDEO", order: 22, videoSrc: "/bank.mp4"},
                {id: 23, lessonId: 31, type: "ASSIST", order: 23, question: "Banks are important financial institutions that help people and businesses manage their money. They offer safe places to store money, provide loans and credit, and charge interest on borrowed funds. Banks also give financial advice, help with investments, and handle foreign exchange. Regulated by central authorities, banks ensure the safety of deposits and support economic stability. Overall, they help with financial transactions and promote financial well-being."},
                {id: 24, lessonId: 31, type: "SELECT", order: 24, question: "What is the primary role of banks in the economy?"},
                {id: 25, lessonId: 32, type: "ASSIST",order: 25 ,question: "A bank's income statement shows how well it has performed financially over a specific period, like a quarter or year. It lists the money the bank earned from interest on loans, service fees, and investments, then subtracts operating costs like salaries and rent to find the operating income. After accounting for other gains or losses and taxes, it calculates the net income or profit. This statement helps understand the bank's profitability and efficiency."},
                {id: 26, lessonId: 32, type: "ASSIST", order: 26, question: "Bank notes & Cheque Bank notes are physical currency issued by central banks, used as legal tender. Checks are written orders to a bank to transfer funds from an account to a recipient. Both facilitate transactions and support economic activities."},
                {id: 27, lessonId: 32, type: "SELECT", order: 27, question: "What is the primary function of bank notes in financial transactions?"},
                {id: 28 ,lessonId: 36, type: "VIDEO", order: 28, videoSrc: "/finance.mp4"},
                {id: 29, lessonId: 36, type: "ASSIST", order: 29, question: "Understanding your money personality means knowing your attitudes and habits towards money. There are four main types: savers, spenders, balancers, and investors. Savers are careful with spending and good at saving but may avoid risks that could lead to growth. Each type has unique strengths and weaknesses that affect financial decisions. Knowing your money personality can help you improve your financial strategies and achieve your goals."},
                {id: 30, lessonId: 36, type: "SELECT", order: 30, question: "Which money personality type is likely to excel in budgeting and prioritize saving, but may avoid taking risks?"},
                {id: 31, lessonId: 37, type: "ASSIST", order: 31, question: "To determine your money personality, consider if you tend to save money or spend it quickly. Savers focus on long-term goals and saving, while spenders enjoy buying things and may not save as much. There are also investors, who seek growth opportunities, and balanced personalities, who mix saving and spending. Your money personality influences how you manage your finances."},
                {id: 32, lessonId: 37, type: "SELECT", order: 32, question: "Balancers are individuals who only focus on saving money and avoid spending or investing."},
                {id: 33, lessonId: 37, type: "SELECT", order: 33, question: "What strategy is suggested for spenders to avoid overspending?"},
                {id: 34 ,lessonId: 42, type: "VIDEO", order: 34, videoSrc: "/insurance.mp4"},
                {id: 35, lessonId: 42, type: "ASSIST", order: 35, question: "What is insurance?Insurance is a type of contract that transfers the risk of something bad happening to an insurance company. In exchange for paying a fee or premium, the insurance company promises to help cover the costs of the unexpected event."},
                {id: 36, lessonId: 42, type: "SELECT", order: 36, question: "What is the primary purpose of insurance?"},
                {id: 37, lessonId: 43, type: "ASSIST", order: 37, question: "How does insurance work? Insurance spreads the risk of financial loss among many people, which is called pooling risk. When a group of people buys insurance, not everyone will face a problem at the same time. The insurance company uses the premiums paid by everyone to cover the losses of those who do experience issues, providing protection against unexpected events for all."},
                {id: 38, lessonId: 43, type: "ASSIST", order: 38, question: "Insurance Terminology:- Premium: The fee you pay for insurance coverage.;Deductible: The amount you must pay before the insurance company covers a claim.;Copay: A fixed payment you make for covered services.;Policy Limit: The maximum amount the insurance company will pay for a claim.;Claim: A request for payment to cover a loss.;Benefit: The money the insurance company agrees to pay for an approved claim."},
                {id: 39, lessonId: 43, type: "SELECT", order: 39, question: "How does insurance work to reduce financial risk?"},
                {id: 40 ,lessonId: 48, type: "VIDEO", order: 40, videoSrc: "/retirement.mp4"},
                {id: 41, lessonId: 48, type: "ASSIST", order: 41, question: "Planning for retirement is important because people are spending as many years retired as they were working. When you retire, your regular paycheck stops, and you need to cover your daily expenses for many years. Social Security provides only a small amount and starts later in life, making it hard to live on alone. To retire early or live comfortably, you should start planning and saving now."},
                {id: 42, lessonId: 48, type: "SELECT", order: 42, question: "Why is it important to plan for retirement?"},
                {id: 43, lessonId: 49, type: "ASSIST", order: 43, question: "When planning for retirement, consider essential expenses like housing, food, transportation, healthcare, entertainment, and insurance/taxes. Use methods like budgeting, the replacement ratio, and online calculators to estimate these costs. To reduce expenses and increase income, consider downsizing, relocating, working part-time, or delaying retirement. Start planning and saving early to ensure a comfortable retirement."},
                {id: 44, lessonId: 49, type: "SELECT", order: 44, question: "Retirement expenses typically decrease as you age and become more settled in your retirement lifestyle."},
                {id: 45, lessonId: 49, type: "SELECT", order: 45, question: "What is a benefit of planning for retirement?"},
                {id: 46, lessonId: 54, type: "ASSIST", order: 46, question: "Situation: You have just started your first job and need to create a budget to manage your expenses. How would you go about creating a budget, and what factors would you consider to ensure you're saving enough money each month? Question: What are the key components of a personal budget, and how can you ensure you stick to it?"},
                {id: 47, lessonId: 5, type:"ASSIST", order: 47, question: "Bonds are debt securities in which an investor loans money to an entity, such as a corporation or government, for a defined period at a fixed interest rate. The issuer, responsible for repaying the bond's principal at maturity, pays periodic interest to the bondholder based on the coupon rate."},
                {id: 48, lessonId: 5, type: "ASSIST", order: 48, question: "The principal, also known as the face value, is the amount borrowed and repaid at the bond's maturity date. Bonds offer investors regular interest income and are considered less risky than stocks, making them a popular choice for portfolio diversification, though they typically yield lower returns."},
                {id:49, lessonId: 5, type: "SELECT", order: 49, question: "What is a bond in the context of finance?"},
                {id: 50, lessonId: 6, type: "ASSIST", order: 50, question: "Bonds are debt securities offering fixed interest payments and return of principal at maturity, while stocks represent ownership in a company, providing potential dividends and capital gains. Bonds are safer with steady income; stocks are riskier but offer higher growth potential."},
                {id: 51, lessonId: 6, type: "SELECT", order: 51, question: "What is the primary difference between bonds and stocks?"},
                {id: 52, lessonId: 7, type: "SELECT", order: 52, question: "What does owning a stock represent?"},
                {id: 53, lessonId: 7, type: "SELECT", order: 53, question: "Which of the following is a characteristic of bonds?"},
                {id: 54, lessonId: 7, type: "SELECT", order: 54, question: "What type of investment typically offers a fixed income with lower risk?"},
                {id: 55, lessonId: 15, type: "SELECT", order: 55, question: "What is the primary purpose of creating a budget?"},
                {id: 56, lessonId: 15, type: "SELECT", order: 55, question: "Which of the following is a fixed expense?"},
                {id: 57, lessonId: 16, type: "ASSIST", order: 57, question: "The 50/30/20 rule is a straightforward budgeting strategy that divides your after-tax income into three categories: 50% for needs, 30% for wants, and 20% for savings and debt repayment."},
                {id: 58, lessonId: 16, type: "ASSIST", order: 58, question: "Needs include essential expenses like housing, utilities, and groceries. Wants cover discretionary spending on things like dining out and entertainment. Savings and debt repayment focus on financial goals such as building an emergency fund, investing, and paying off debts. ."},
                {id: 59, lessonId: 16, type: "ASSIST", order: 59, question: "This rule helps ensure a balanced approach to managing finances, promoting financial stability, and preparing for future needs"},
                {id: 60, lessonId: 17, type: "SELECT", order: 60, question: "What does owning a stock represent?"},
                {id: 61, lessonId: 17, type: "SELECT", order: 61, question: "Which category includes expenses like dining out and entertainment?"},
                {id: 62, lessonId: 17, type: "SELECT", order: 62, question: "What are examples of needs according to the 50/30/20 rule?"},
                {id: 63, lessonId: 18, type: "SELECT", order: 63, question: "What financial goals are included in the 20% allocation for savings and debt repayment?"},
                {id: 64, lessonId: 18, type: "SELECT", order: 64, question: "The 50/30/20 rule divides after-tax income into three categories. Which of the following is NOT one of those categories?"},
                {id: 65, lessonId: 20, type: "ASSIST", order: 65, question: "There are several types of loans, each serving different purposes. Personal loans are unsecured and can be used for various personal expenses like medical bills, home renovations, or vacations. Mortgage loans are secured and specifically for purchasing or refinancing a home."},
                {id: 66, lessonId: 20, type: "ASSIST", order: 66, question: "Auto loans, also secured, are used to finance vehicle purchases. Student loans help cover education-related expenses, while business loans are intended for business purposes such as starting or expanding a business. Payday loans are short-term, high-interest loans meant to cover immediate expenses until the borrower's next paycheck."},
                {id: 67, lessonId: 20, type: "SELECT", order: 67, question: "Which type of loan is unsecured and can be used for various personal expenses?"},
                {id: 68, lessonId: 21, type: "SELECT", order: 68, question: "What are mortgage loans specifically used for?"},
                {id: 69, lessonId: 21, type: "SELECT", order: 69, question: "Which type of loan is secured and used to finance the purchase of a vehicle?"},
                {id: 70, lessonId: 21, type: "SELECT", order: 70, question: "What purpose do student loans serve?"},
                {id: 71, lessonId: 22, type: "SELECT", order: 71, question: "Which type of loan is intended for business purposes, such as starting or expanding a business?"},
                {id: 72, lessonId: 22, type: "SELECT", order: 72, question: "What is the characteristic of payday loans?"},
                {id: 73, lessonId: 23, type: "ASSIST", order: 73, question: "Understanding key loan terms can help navigate the borrowing process. The principal is the original amount borrowed, while the interest rate is the percentage charged by the lender for borrowing. The term is the length of time to repay the loan."},
                {id: 74, lessonId: 23, type: "ASSIST", order: 74, question: "Collateral is an asset pledged to secure the loan, which the lender can seize if the borrower defaults. The APR (Annual Percentage Rate) represents the total cost of borrowing, including interest and fees, as an annual percentage. A fixed rate remains the same throughout the loan term, whereas a variable rate can fluctuate based on market conditions."},
                {id: 75, lessonId: 23, type: "SELECT", order: 75, question: "What is the principal in a loan?"},
                {id: 76, lessonId: 24, type: "SELECT", order: 76, question: "What is the term in a loan agreement?"},
                {id: 77, lessonId: 24, type: "SELECT", order: 77, question: "What is collateral in the context of a loan?"},
                {id: 78, lessonId: 24, type: "SELECT", order: 78, question: "What does APR (Annual Percentage Rate) include?"},
                {id: 79, lessonId: 27, type: "ASSIST", order: 79, question: "Real-World Case Study: The Early Bird Advantage.: Emily's Journey-Start Age: 25, Annual Contribution: $5,000, Investment Period: 40 years, Total Contributions: $200,000, Estimated Portfolio Value at 65: $1,068,048"},
                {id: 80, lessonId: 27, type: "ASSIST", order: 80, question: "Real-World Case Study: The Early Bird Advantage.: Jack's Journey-Start Age: 35, Annual Contribution: $5,000, Investment Period: 30 years, Total Contributions: $150,000, Estimated Portfolio Value at 65: $505,365. Conclusion: Starting early maximizes investment growth through compound interest. Emily's early start resulted in a portfolio more than double Jack's, despite equal annual contributions. This underscores the importance of early saving and investing."},
                {id: 81, lessonId: 27, type: "SELECT", order: 81, question: "What is the estimated portfolio value for Emily at age 65, given she started investing $5,000 annually at age 25 with an average annual return of 7%?"},
                {id: 82, lessonId: 28, type: "ASSIST", order: 82, question: "Saving and Investing Options-Bank Accounts: Safe, low-interest savings. CDs: Higher interest, fixed term. Stocks: Buy shares, potential profit or loss. Bonds: Lend money, earn interest. Mutual Funds: Invest in a diverse mix via pooled money."},
                {id: 83, lessonId: 28, type: "SELECT", order: 83, question: "Which investment option involves pooling money from many investors to buy a diverse mix of stocks, bonds, or other investments?"},
                {id: 84, lessonId: 29, type: "ASSIST", order: 84, question: "Savings vs. Investing. Consider these factors: Liquidity: Savings are highly liquid; investments can be less so. Risk: Savings are low-risk; stocks and bonds carry higher risk. Return: Savings have low returns; stocks and bonds offer higher potential returns.Time Horizon: Short-term needs favor savings; long-term goals benefit from investing."},
                {id: 85, lessonId: 29, type: "SELECT", order: 85, question: "Which financial option typically offers higher potential returns?"},
                {id: 86, lessonId: 30, type: "ASSIST", order: 86, question: "How saving and investing can work together? Saving and investing can complement each other in helping you achieve your financial goals. For example, you might save money for emergencies and short-term goals, while investing for long-term goals like retirement. By having both savings and investments, you can ensure that you have money available for immediate needs and also have your money growing for the future."},
                {id: 87, lessonId: 30, type: "ASSIST", order: 87, question: "Tips for Balancing Saving and Investing: Budget: Track income and expenses to allocate for saving and investing. Emergency Fund: Save 3-6 months' living expenses for emergencies. Goals: Set clear financial goals for short and long term.Diversification: Spread investments to reduce risk. Review: Regularly assess and adjust strategies."},
                {id: 88, lessonId: 30, type: "SELECT", order: 88, question: "How much should you ideally save in an emergency fund?"},
                {id: 89, lessonId: 33, type: "ASSIST", order: 89, question: "Types of Accounts: Understanding different types of bank accounts such as savings, checking, money market accounts, and their respective features like interest rates, fees, minimum balance requirements, and accessibility for transactions and withdrawals."},
                {id: 90, lessonId: 33, type: "ASSIST", order: 90, question: "Banking Services: Exploring various services offered by banks, including loans, credit cards, investment products, and online banking functionalities. give more"},
                {id: 91, lessonId: 33, type: "SELECT", order: 91, question: "Which type of account typically offers the highest interest rates?"},
                {id: 92, lessonId: 34, type: "ASSIST", order: 92, question: "Financial Regulations and Consumer Protection: This topic delves into the regulatory framework governing banks and protecting consumers. It includes laws like capital requirements and deposit insurance that banks must adhere to. Consumer protection laws ensure fair treatment in banking transactions and privacy of financial information. Compliance with these regulations is crucial for maintaining trust and stability in the financial system, ensuring transparency and accountability in banking operations. Understanding these regulations provides insight into how banks operate within legal boundaries while safeguarding consumer rights and interests."},
                {id: 93, lessonId: 34, type: "SELECT", order: 93, question: "What regulatory framework governs banks' adherence to capital requirements and deposit insurance?"},
                {id: 94, lessonId: 34, type: "SELECT", order: 94, question: "Which aspect of financial regulations focuses on protecting consumer rights and ensuring fair treatment in banking transactions?"},
                {id: 95, lessonId: 35, type: "ASSIST", order: 95, question: "Importance of Credit Scores in Banking. Understanding Credit Scores: Credit scores play a crucial role in banking and financial decisions, influencing loan approvals, interest rates, and credit card offers. Maintaining a good credit score is essential for accessing favorable financial products and terms."},
                {id: 96, lessonId: 35, type: "SELECT", order: 96, question: "A higher credit score typically results in lower interest rates on loans and credit cards."},
                {id: 97, lessonId: 38, type: "ASSIST", order: 97, question: "To write SMART financial goals: Specific: Clearly define what you want to achieve, like saving for an emergency fund. Measurable: Set clear criteria to track progress, such as saving a specific amount regularly. Achievable: Ensure the goal is realistic based on your current financial situation. Relevant: Align the goal with your financial priorities and needs. Time-bound: Set a deadline to achieve the goal, creating accountability and urgency."},
                {id: 98, lessonId: 38, type: "SELECT", order: 98, question: "What does the R in SMART financial goals stand for?"},
                {id: 99, lessonId: 39, type: "ASSIST", order: 99, question: "SMART Financial Goals Examples: Emergency Fund:SMART Goal: Save $3,000 for an emergency fund by setting aside $150 from each biweekly paycheck for 10 weeks, aiming to prepare for unexpected expenses and avoid debt. Paying Off Debt: SMART Goal: Pay off $5,000 credit card debt by increasing monthly payments by $250 for 20 months, aiming to save on interest and improve credit score."},
                {id: 100, lessonId: 39, type: "ASSIST", order: 100, question: "Buying a Car: SMART Goal: Purchase a $15,000 used car by saving $500 from each monthly paycheck for 30 months, aiming for increased independence. Saving for Retirement: SMART Goal: Save $500,000 for retirement by contributing 10% of income to a 401(k) plan for 25 years, aiming for a comfortable and secure post-work lifestyle."},
                {id: 101, lessonId: 39, type: "SELECT", order: 101, question: "Which is an example of a SMART financial goal?"},
                {id: 102, lessonId: 40, type: "ASSIST", order: 102, question: "Short-Term Goals: Achievable within a year, such as buying a new phone or saving for a trip. Low-risk, focusing on budgeting and saving in accessible accounts. Medium-Term Goals: Achievable in one to five years, like buying a car or saving for college. Moderate-risk, involving planning and investment in diversified options. Long-Term Goals: Achievable in more than five years, such as buying a house or saving for retirement. High-risk, requiring income projection and investment in growth-oriented assets"},
                {id: 103, lessonId: 40, type: "SELECT", order: 104, question: "You want to save money for your mom's birthday gift. Identify the goal as a short, medium, or long term goal."},
                {id: 105, lessonId: 44, type: "ASSIST", order: 105, question: "Insurance Terminology : Premium: Payment for coverage. Deductible: Out-of-pocket amount before coverage. Co-pay: Fixed fee per covered service. Policy Limit: Maximum claim payout. Claim: Request for coverage of a loss. Benefit: Payment upon successful claim."},
                {id: 106, lessonId: 44, type: "ASSIST", order: 106, question: "Example of Insurance Terms in Use: For instance, in a health insurance policy with a deductible of $500, if someone undergoes a surgery costing $5,000, they would need to pay the initial $500 out of pocket before the insurance covers the remaining $4,500 of the medical expenses."},
                {id: 107, lessonId: 44, type: "SELECT", order: 107, question: "In insurance, what does the term deductible refer to?"},
                {id: 108, lessonId: 45, type: "ASSIST", order: 108, question: "Insurance companies use math, specifically probability and statistics, to figure out how likely it is that someone will have a loss that they need to help pay for. They look at information about a person, like their age, where they live, and other factors, to estimate how likely it is that they'll experience a covered loss. Then, they use this information to set the premium price. The higher the risk, the higher the premium."},
                {id: 109, lessonId: 45, type: "SELECT", order: 109, question: "How do insurance companies determine the price of premiums?"},
                {id: 110, lessonId: 46, type: "ASSIST", order: 110, question: "In an insurance transaction, key players include: Insured: You, the purchaser of the insurance policy. Insurer: The company selling the policy and responsible for covering losses. Agent: Assists in purchasing insurance, representing the insurer or working independently. Underwriter: Determines the risk the insurer will accept and sets the premium price."},
                {id: 111, lessonId: 46, type: "SELECT", order: 111, question: "Who at an insurance company decides how much risk they are willing to accept and sets the premium price?"},
                {id: 112, lessonId: 47, type: "ASSIST", order: 112, question: "Why do we need health insurance? Imagine you suddenly get sick and need to see a doctor. Without health insurance, you might have to pay hundreds or even thousands of dollars for your visit and any tests or treatments you need. But with health insurance, you pay a smaller amount, called a premium, every month, and the insurance company helps cover the rest of the cost. This way, you don't have to worry about large medical bills, and you can focus on getting better."},
                {id: 113, lessonId: 47, type: "SELECT", order: 113, question: "Why is health insurance important?"},
                {id: 114, lessonId: 50, type: "ASSIST", order: 114, question: "Building a foundation for retirement: Preparing for retirement early provides flexibility to achieve your desired future lifestyle, whether it's traveling extensively or transitioning to part-time work pursuing personal passions. Starting to save early in your career ensures greater financial security and options for retirement plans."},
                {id: 115, lessonId: 50, type: "SELECT", order: 115, question: "Why is it beneficial to start saving for retirement early in your career?"},
                {id: 116, lessonId: 51, type: "ASSIST", order: 116, question: "The effect of time on your retirement account:When young, starting to save for retirement, even with a small amount, can significantly grow savings over decades due to the beneficial impact of time on investments."},
                {id: 117, lessonId: 51, type: "SELECT", order: 117, question: "Why is it advantageous to start saving for retirement at a young age?"},
                {id: 118, lessonId: 51, type: "SELECT", order: 118, question: "How does time affect retirement savings?"},
                {id: 119, lessonId: 52, type: "ASSIST", order: 119, question: "When you think about retirement, you might imagine yourself traveling the world, spending time with your family, or finally having the time to pursue your hobbies. But, to enjoy your retirement, you must have a steady source of income. In this article, we'll discuss the main sources of income during retirement and how they work."},
                {id: 120, lessonId: 52, type: "SELECT", order: 120, question: "What is essential to enjoy retirement?"},
                {id: 121, lessonId: 53, type: "SELECT", order: 121, question: "Benefits of Planning for Retirement: Planning ensures sufficient income and savings to cover expenses and desired activities in retirement, maintaining your standard of living."},
                {id: 122, lessonId: 53, type: "SELECT", order: 122, question: "What does planning for retirement help ensure?"},
        ]);

        // challenge options
        await db.insert(schema.challengeOptions).values([
                { id: 1, challengeId: 1, correct: false, text: "Read Aloud", audioSrc: "/whatAreStocks.mp3" },
                { id: 2, challengeId: 1, correct: true, text: "Got it" },
                { id: 3, challengeId: 2, correct: false, text: "Stocks are loans given to companies by investors" },
                { id: 4, challengeId: 2, correct: false, text: "Stocks are government-issued bonds" },
                {id: 5, challengeId: 2, correct: true, text: "Stocks represent ownership in a company and a claim on part of its assets and earnings."},
                {id: 6, challengeId: 2, correct: false, text: "Stocks are fixed-income investments"},
                {id: 7, challengeId: 3, correct: false, text: "Didn't get it"},
                {id: 8, challengeId: 3, correct: true, text: "Got it"},
                {id: 9, challengeId: 4, correct: false, text: "A guarantee fixed income"},
                {id: 10, challengeId: 4, correct: true,  text: "Ownership in a company and a claim on part of its assets and earnings"},
                {id: 11, challengeId: 4, correct: false, text: "A loan to the company"},
                {id: 12, challengeId: 4, correct: false, text: "A government bond"},
                { id: 13, challengeId: 5, correct: false, text: "Read Aloud", audioSrc: "/whatAreStocks.mp3" },
                { id: 14, challengeId: 5, correct: true, text: "Got it" },
                { id: 15, challengeId: 6, correct: false, text: "Stocks are loans given to companies by investors" },
                { id: 16, challengeId: 6, correct: false, text: "Stocks are government-issued bonds" },
                {id: 17, challengeId: 6, correct: true, text: "Stocks represent ownership in a company and a claim on part of its assets and earnings."},
                {id: 18, challengeId: 6, correct: false, text: "Stocks are fixed-income investments"},
                {id: 19, challengeId: 7, correct: false, text: "Didn't get it"},
                {id: 20, challengeId: 7, correct: true, text: "Got it"},
                {id: 21, challengeId: 8, correct: false, text: "A guarantee fixed income"},
                {id: 22, challengeId: 8, correct: true,  text: "Ownership in a company and a claim on part of its assets and earnings"},
                {id: 23, challengeId: 8, correct: false, text: "A loan to the company"},
                {id: 24, challengeId: 8, correct: false, text: "A government bond"},
                {id: 25, challengeId: 9, correct: false, text: "Read Aloud", audioSrc: "/budget.mp3" },
                {id: 26, challengeId: 9, correct: true, text: "Got it"},
                {id: 27, challengeId: 10, correct: false, text: "To show you how much debt you can accumulate"},
                {id: 28, challengeId: 10, correct: true, text: "To help you manage your money by showing income, expenses, and savings" },
                {id: 29, challengeId: 10, correct: false, text: "To determine how much money you can borrow"},
                {id: 30, challengeId: 10, correct: false, text: "To track your spending without any financial planning"},
                {id: 31, challengeId: 11, correct: false, text: "Didn't get it"},
                {id: 32, challengeId: 11, correct: true, text: "Got it"},
                {id: 33, challengeId: 12, correct: false, text: "Money you save for future goals"},
                {id: 34, challengeId: 12, correct: false, text: "Money you earn from a job"},
                {id: 35, challengeId: 12, correct: true, text: "Money you spend on things like bills, food, and entertainment"},
                {id: 36, challengeId: 12, correct: false, text: "Money you receive as a gift"},
                {id: 37, challengeId: 13, correct: false, text: "Read Aloud", audioSrc: "/loans.mp3"},
                {id: 38, challengeId: 13, correct: true, text: "Got it"},
                {id: 39 , challengeId: 14, correct: false, text: "Read Aloud", audioSrc: "/interest.mp3"},
                {id: 40, challengeId: 14, correct: true, text: "Got it"},
                {id: 41, challengeId: 15, correct: false, text: "The amount of money you receive for saving money"},
                {id: 42, challengeId: 15, correct: true, text: "The amount of money you pay to the lender for using their money, usually expressed as a percentage of the amount borrowed"},
                {id: 43, challengeId: 15, correct: false, text: "The total amount of the loan you borrow"},
                {id: 44, challengeId: 15, correct: false, text: "A fee charged for early repayment of a loan"},
                {id: 45, challengeId: 17, correct: false, text: "Read Aloud", audioSrc: "/inv1.mp3"},
                {id:46, challengeId: 17, correct: true, text: "Got It"},
                {id: 47, challengeId: 16, correct: false, text: "Didn't get it"},
                {id: 48, challengeId: 16, correct: true, text: "Got it"},
                {id: 49 ,challengeId: 18, correct: false, text: "Keeping money in safe, accessible accounts for immediate use."},
                {id: 50 ,challengeId: 18, correct: true, text: "Putting money into assets with the expectation that their value will grow over time."},
                {id: 51 ,challengeId: 18, correct: false, text: "Storing money in a way that ensures it remains the same amount."},
                {id: 52 ,challengeId: 18, correct: false, text: "Avoiding any risk and ensuring 100% capital preservation."},
                {id: 53, challengeId: 19, correct: false, text: "Read aloud", audioSrc: "/inv2.mp3"},
                {id: 54, challengeId: 19, correct: true ,text: "Got it"},
                {id: 55, challengeId: 20, correct: false, text: "Read aloud", audioSrc: "/inv3.mp3"},
                {id: 56, challengeId: 20, correct: true, text: "Got it"},
                {id: 57, challengeId: 21, correct: false, text: "Savings accounts offer higher returns compared to investments."},
                {id: 58, challengeId: 21, correct: true, text: "Saving involves keeping money in secure accounts with easy access, while investing involves putting money into assets with the goal of higher returns over time."},
                {id: 59, challengeId: 21, correct: false, text: "Investing ensures 100% capital preservation, whereas saving involves some degree of risk."},
                {id: 60, challengeId: 21, correct: false, text: "Savings are typically for short-term goals, while investments are for long-term financial planning."},
                {id: 61, challengeId: 22, correct: false ,text: "Didn't get it"},
                {id: 62, challengeId: 22, correct: true, text: "Got it"},
                {id: 63, challengeId: 23, correct: false, text: "Read Aloud", audioSrc: "/bank1.mp3"},
                {id: 64, challengeId: 23, correct: true, text: "Got it"},
                {id: 65, challengeId: 24, correct: false, text: "Promoting environmental sustainability initiatives."},
                {id: 66, challengeId: 24, correct: false, text: "Regulating government policies on taxation."},
                {id: 67, challengeId: 24, correct: true, text: "Offering deposit accounts and loans to individuals and businesses."},
                {id: 68, challengeId: 24, correct: false, text: "Providing entertainment services to customers."},
                {id: 69, challengeId: 25, correct: false, text: "Read Aloud", audioSrc: "/bank2.mp3"},
                {id: 70, challengeId: 25, correct: true, text: "Got it"},
                {id: 71, challengeId: 26, correct: false, text: "Read Aloud", audioSrc: "/bank3.mp3"},
                {id: 72, challengeId: 26, correct: true, text: "Got it"},
                {id: 73, challengeId: 27, correct: false, text: "Acting as digital currency."},
                {id: 74, challengeId: 27, correct: false, text: "Providing investment opportunities."},
                {id: 75, challengeId: 27, correct: true, text: "Serving as legal tender."},
                {id: 76, challengeId: 27, correct: false, text: "Facilitating online payments."},
                {id: 77, challengeId: 28, correct: false ,text: "Didn't get it"},
                {id: 78, challengeId: 28, correct: true, text: "Got it"},
                {id: 79, challengeId: 29, correct: false, text: "Read Aloud", audioSrc: "/fin1.mp3"},
                {id: 80, challengeId: 29, correct: true, text: "Got it"},
                {id: 81, challengeId: 30, correct: false, text: "Spender"},
                {id: 82, challengeId: 30, correct: false, text: "Balancer"},
                {id: 83, challengeId: 30, correct: false, text: "Investor"},
                {id: 84, challengeId: 30, correct: true, text: "Saver"},
                {id: 85, challengeId: 31, correct: false, text: "Read Aloud", audioSrc: "/fin2.mp3"},
                {id: 86, challengeId: 31, correct: true, text: "Got it"},
                {id: 87, challengeId: 32, correct: false, text: "False"},
                {id: 88, challengeId: 32, correct: true, text: "True"},
                {id: 89, challengeId: 33, correct: true, text: "Set aside a portion of income for savings or investments before spending"},
                {id: 90, challengeId: 33, correct: false, text: "Use credit cards for every purchase"},
                {id: 91, challengeId: 33, correct: false, text: "Avoid setting any spending limits"},
                {id: 92, challengeId: 33, correct: false, text: "Rely on impulse buying for all purchases"},
                {id: 93, challengeId: 34, correct: false ,text: "Didn't get it"},
                {id: 94, challengeId: 34, correct: true, text: "Got it"},
                {id: 95, challengeId: 35, correct: false, text: "Read Aloud", audioSrc: "/insurance1.mp3"},
                {id: 96, challengeId: 35, correct: true, text: "Got it"},
                {id: 97, challengeId: 36, correct: false, text: "To invest your money for long-term growth."},
                {id: 98, challengeId: 36, correct: false, text: "To provide a fixed income stream during retirement"},
                {id: 99, challengeId: 36, correct: false, text: "To offer tax benefits on your yearly earnings."},
                {id: 100, challengeId: 36, correct: true, text: "To guarantee financial protection against unexpected events"},
                {id: 101, challengeId: 37, correct: false, text: "Read Aloud", audioSrc: "/insurance2.mp3"},
                {id: 102, challengeId: 37, correct: true, text: "Got it"},
                {id: 103, challengeId: 38, correct: false, text: "Read Aloud", audioSrc: "/insurance3.mp3"},
                {id: 104, challengeId: 38, correct: true, text: "Got it"},
                {id: 105, challengeId: 39, correct: false, text: "By offering discounts on repairs and replacements"},
                {id: 106, challengeId: 39, correct: false, text: "By providing legal representation in case of accidents."},
                {id: 107, challengeId: 39, correct: true, text: "By spreading the cost of potential losses among a large group."},
                {id: 108, challengeId: 39, correct: false, text: "By guaranteeing a specific amount of money in case of an event."},
                {id: 109, challengeId: 40, correct: false ,text: "Didn't get it"},
                {id: 110, challengeId: 40, correct: true, text: "Got it"},
                {id: 111, challengeId: 41, correct: false, text: "Read Aloud", audioSrc: "/ret1.mp3"},
                {id: 112, challengeId: 41, correct: true, text: "Got it"},
                {id: 113, challengeId: 42, correct: true, text: "To ensure you have enough income to cover your expenses after you stop working."},
                {id: 114, challengeId: 42, correct: false, text: "To invest your money for long-term growth"},
                {id: 115, challengeId: 42, correct: true, text: "To pay off all your debts before you retire."},
                {id: 116, challengeId: 42, correct: false, text: "To travel the world extensively during your golden years."},
                {id: 117, challengeId: 43, correct: false, text: "Read Aloud", audioSrc: "/ret2.mp3"},
                {id: 118, challengeId: 43, correct: true, text: "Got it"},
                {id: 119, challengeId: 44, correct: false, text: "True"},
                {id: 120, challengeId: 44, correct: true, text: "False"},
                {id: 121, challengeId: 45, correct: true, text: "Having the peace of mind of knowing your future expenses are covered."},
                {id: 122, challengeId: 45, correct: false, text: "Avoiding work altogether after you retire."},
                {id: 123, challengeId: 45, correct: true, text: "Needing to rely on your children for financial support."},
                {id: 124, challengeId: 45, correct: false, text: "Experiencing a higher level of stress during your working years."},
                {id: 125, challengeId: 46, correct: true, text: "Track your monthly income and expenses, and allocate specific amounts for different categories such as housing, food, transportation, and savings"},
                {id: 126, challengeId: 46, correct: false, text: "Spend freely and check your account balance occasionally to make sure you don’t run out of money"},
                {id: 127, challengeId: 47, correct: false, text: "Read Aloud", audioSrc: "/stocks1.mp3"},
                {id: 128, challengeId: 47, correct: true, text: "Got it"},
                {id: 129, challengeId: 48, correct: false, text: "Read Aloud", audioSrc: "/stocks2.mp3"},
                {id: 130, challengeId: 48, correct: true, text: "Got it"},
                {id: 131, challengeId: 49, correct: true, text: "A debt security where an investor loans money to an entity for a defined period at a fixed interest rate."},
                {id: 132, challengeId: 49, correct: false, text: "A type of equity security where an investor buys a share of a company."},
                {id: 133, challengeId: 49, correct: false, text: "A savings account that pays interest based on the performance of the stock market."},
                {id: 134, challengeId: 49, correct: false, text: "A type of real estate investment where an investor purchases property to rent out."},
                {id: 135, challengeId: 50, correct: false, text: "Read Aloud", audioSrc: "/stocks3.mp3"},
                {id: 136, challengeId: 50, correct: true, text: "Got it"},
                {id: 137, challengeId: 51, correct: false, text: "Bonds represent ownership in a company, while stocks are debt securities."},
                {id: 138, challengeId: 51, correct: false, text: "Bonds offer potential dividends and capital gains, while stocks provide fixed interest payments."},
                {id: 139, challengeId: 51, correct: true, text: "Bonds are safer with steady income, while stocks are riskier with higher growth potential."},
                {id: 140, challengeId: 51, correct: false, text: "Bonds are riskier with higher growth potential, while stocks offer steady income."},
                {id: 141, challengeId: 52, correct: false, text: "A loan to a company."},
                {id: 142, challengeId: 52, correct: true, text: "Ownership in a company."},
                {id: 143, challengeId: 52, correct: false, text: "A fixed interest payment from a company."},
                {id: 144, challengeId: 52, correct: false, text: "A bond issued by a company."},
                {id: 145, challengeId: 53, correct: false, text: "They represent ownership in a company."},
                {id: 146, challengeId: 53, correct: false, text: "They provide periodic interest payments and return of principal at maturity."},
                {id: 147, challengeId: 53, correct: false, text: "They fluctuate in value based on company performance."},
                {id: 148, challengeId: 53, correct: true, text: "They provide periodic interest payments and return of principal at maturity."},
                {id: 149, challengeId: 54, correct: false, text: "Stocks"},
                {id: 150, challengeId: 54, correct: false, text: "Real estate"},
                {id: 151, challengeId: 54, correct: true, text: "Bonds"},
                {id: 152, challengeId: 54, correct: false, text: "Mutual funds"},
                {id: 153, challengeId: 55, correct: false, text: "To restrict spending"},
                {id: 154, challengeId: 55, correct: false, text: "To increase debt"},
                {id: 155, challengeId: 55, correct: false, text: "To save money in a bank"},
                {id: 156, challengeId: 55, correct: true, text: "To plan for future expenses"},
                {id: 157, challengeId: 56, correct: false, text: "Groceries"},
                {id: 158, challengeId: 56, correct: false, text: "Entertainment"},
                {id: 159, challengeId: 56, correct: true, text: "Rent"},
                {id: 160, challengeId: 56, correct: false, text: "Utility bills"},
                {id: 161, challengeId: 57, correct: false, text: "Read Aloud", audioSrc: "/budget1.mp3"},
                {id: 162, challengeId: 57, correct: true, text: "Got it"},
                {id: 163, challengeId: 58, correct: false, text: "Read Aloud", audioSrc: "/budget2.mp3"},
                {id: 164, challengeId: 58, correct: true, text: "Got it"},
                {id: 165, challengeId: 59, correct: false, text: "Read Aloud", audioSrc: "/budget3.mp3"},
                {id: 166, challengeId: 59, correct: true, text: "Got it"},
                {id: 167, challengeId: 60, correct: true, text: "Spend 50% on needs, 30% on wants, and save 20%"},
                {id: 168, challengeId: 60, correct: false, text: "Spend 50% on wants, 30% on needs, and save 20%"},
                {id: 169, challengeId: 60, correct: false, text: "Save 50%, spend 30%, and invest 20%"},
                {id: 170, challengeId: 60, correct: false, text: "Spend 50% on needs, save 30%, and invest 20%"},
                {id: 171, challengeId: 61, correct: false, text: "Needs"},
                {id: 172, challengeId: 61, correct: true, text: "Wants"},
                {id: 173, challengeId: 61, correct: false, text: "Savings"},
                {id: 174, challengeId: 61, correct: false, text: "Debt repayment"},
                {id: 175, challengeId: 62, correct: false, text: "Dining out and movies"},
                {id: 176, challengeId: 62, correct: false, text: "Vacations and hobbies"},
                {id: 177, challengeId: 62, correct: false, text: "Luxury items and subscriptions"},
                {id: 178, challengeId: 62, correct: true, text: "Housing, utilities, and groceries"},
                {id: 179, challengeId: 63, correct: false, text: "Dining out and entertainment"},
                {id: 180, challengeId: 63, correct: false, text: "Paying for utilities and groceries"},
                {id: 181, challengeId: 63, correct: true, text: "Building an emergency fund and investing"},
                {id: 182, challengeId: 63, correct: false, text: "Buying luxury items and subscriptions"},
                {id: 183, challengeId: 64, correct: false, text: "Needs"},
                {id: 184, challengeId: 64, correct: true, text: "Investments"},
                {id: 185, challengeId: 64, correct: false, text: "Savings"},
                {id: 186, challengeId: 64, correct: false, text: "Wants"},
                {id: 187, challengeId: 65, correct: false, text: "Read Aloud", audioSrc: "/loans1.mp3"},
                {id: 188, challengeId: 65, correct: true, text: "Got it"},
                {id: 189, challengeId: 66, correct: false, text: "Read Aloud", audioSrc: "/loans2.mp3"},
                {id: 190, challengeId: 66, correct: true, text: "Got it"},
                {id: 191, challengeId: 67, correct: false, text: "Mortgage Loans"},
                {id: 192, challengeId: 67, correct: false, text: "Auto Loans"},
                {id: 193, challengeId: 67, correct: true, text: "Personal Loans"},
                {id: 194, challengeId: 67, correct: false, text: "Student Loans"},
                {id: 195, challengeId: 68, correct: false, text: "Purchasing a vehicle"},
                {id: 196, challengeId: 68, correct: false, text: "Home renovations"},
                {id: 197, challengeId: 68, correct: false, text: "Paying medical bills"},
                {id: 198, challengeId: 68, correct: true, text: "Purchasing or refinancing a home"},
                {id: 199, challengeId: 69, correct: false, text: "Personal Loans"},
                {id: 200, challengeId: 69, correct: true, text: "Auto Loans"},
                {id: 201, challengeId: 69, correct: false, text: "Student Loans"},
                {id: 202, challengeId: 69, correct: false, text: "Payday Loans"},
                {id: 203, challengeId: 70, correct: false, text: "Home renovations"},
                {id: 204, challengeId: 70, correct: false, text: "Business expansion"},
                {id: 205, challengeId: 70, correct: true, text: "Education-related expenses"},
                {id: 206, challengeId: 70, correct: false, text: "Immediate expenses until next paycheck"},
                {id: 207, challengeId: 71, correct: true, text: "Business Loans"},
                {id: 208, challengeId: 71, correct: false, text: "Mortgage Loans"},
                {id: 209, challengeId: 71, correct: false, text: "Personal Loans"},
                {id: 210, challengeId: 71, correct: false, text: "Auto Loans"},
                {id: 211, challengeId: 72, correct: false, text: "Long-term, low-interest loans"},
                {id: 212, challengeId: 72, correct: false, text: "Secured loans for home purchases"},
                {id: 213, challengeId: 72, correct: true, text: "Short-term, high-interest loans meant to cover immediate expenses until the next paycheck"},
                {id: 214, challengeId: 72, correct: false, text: "Loans for purchasing a vehicle"},
                {id: 215, challengeId: 73, correct: false, text: "Read aloud", audioSrc: "/loans4.mp3"},
                {id: 216, challengeId: 73, correct: true, text: "Got it"},
                {id: 217, challengeId: 74, correct: false, text: "Read aloud", audioSrc: "/loans5.mp3"},
                {id: 218, challengeId: 74, correct: true, text: "Got it"},
                {id: 219, challengeId: 75, correct: false, text: "The total cost of borrowing"},
                {id: 220, challengeId: 75, correct: false, text: "The percentage of the principal charged by the lender"},
                {id: 221, challengeId: 75, correct: true, text: "The original amount of money borrowed"},
                {id: 222, challengeId: 75, correct: false, text: "The length of time over which the loan must be repaid"},
                {id: 223, challengeId: 76, correct: false, text: "The original amount of money borrowed"},
                {id: 224, challengeId: 76, correct: false, text: "The percentage of the principal charged by the lender"},
                {id: 225, challengeId: 76, correct: false, text: "The total cost of borrowing, including fees"},
                {id: 226, challengeId: 76, correct: true, text: "The length of time over which the loan must be repaid"},
                {id: 227, challengeId: 77, correct: true, text: "An asset pledged by the borrower to secure the loan"},
                {id: 228, challengeId: 77, correct: false, text: "The total cost of borrowing"},
                {id: 229, challengeId: 77, correct: false, text: "The percentage of the principal charged by the lender"},
                {id: 230, challengeId: 77, correct: false, text: "The length of time to repay the loan"},
                {id: 231, challengeId: 78, correct: false, text: "Only the interest on the principal"},
                {id: 232, challengeId: 78, correct: false, text: "The original amount of money borrowed"},
                {id: 233, challengeId: 78, correct: true, text: "The total cost of borrowing, including interest and fees, expressed as an annual percentage"},
                {id: 234, challengeId: 78, correct: false, text: "The length of time over which the loan must be repaid"},
                {id: 235, challengeId: 79, correct: false, text: "Read aloud", audioSrc: "/inv4.mp3"},
                {id: 236, challengeId: 79, correct: true, text: "Got it"},
                {id: 237, challengeId: 80, correct: false, text: "Read aloud", audioSrc: "/inv5.mp3"},
                {id: 238, challengeId: 80, correct: true, text: "Got it"},
                {id: 239, challengeId: 81, correct: false, text: "$505365"},
                {id: 240, challengeId: 81, correct: false, text: "$200000"},
                {id: 241, challengeId: 81, correct: true, text: "$1068048"},
                {id: 242, challengeId: 81, correct: false, text: "$150000"},
                {id: 243, challengeId: 82, correct: false, text: "Read aloud", audioSrc: "/inv6.mp3"},
                {id: 244, challengeId: 82, correct: true, text: "Got it"},
                {id: 245, challengeId: 83, correct: false, text: " Bank Accounts"},
                {id: 246, challengeId: 83, correct: false, text: "Certificates of Deposit (CDs)"},
                {id: 247, challengeId: 83, correct: false, text: "Bonds"},
                {id: 248, challengeId: 83, correct: true, text: "Mutual Funds"},
                {id: 249, challengeId: 84, correct: false, text: "Read aloud", audioSrc: "/inv7.mp3"},
                {id: 250, challengeId: 84, correct: true, text: "Got it"},
                {id: 251, challengeId: 85, correct: false, text: "Savings accounts"},
                {id: 252, challengeId: 85, correct: true, text: "Stocks"},
                {id: 253, challengeId: 85, correct: false, text: "Certificates of Deposit (CDs)"},
                {id: 254, challengeId: 85, correct: false, text: "None"},
                {id: 255, challengeId: 86, correct: false, text: "Read aloud", audioSrc: "/inv8.mp3"},
                {id: 256, challengeId: 86, correct: true, text: "Got it"},
                {id: 257, challengeId: 87, correct: false, text: "Read aloud", audioSrc: "/inv9.mp3"},
                {id: 258, challengeId: 87, correct: true, text: "Got it"},
                {id: 259, challengeId: 88, correct: false, text: "One month's living expenses"},
                {id: 260, challengeId: 88, correct: false, text: "One year's living expenses"},
                {id: 261, challengeId: 88, correct: true, text: "Three to six months' living expenses"},
                {id: 262, challengeId: 88, correct: false, text: "No emergency fund needed"},
                {id: 263, challengeId: 89, correct: false, text: "Read aloud", audioSrc: "/bank4.mp3"},
                {id: 264, challengeId: 89, correct: true, text: "Got it"},
                {id: 265, challengeId: 90, correct: false, text: "Read aloud", audioSrc: "/bank5.mp3"},
                {id: 266, challengeId: 90, correct: true, text: "Got it"},
                {id: 267, challengeId: 91, correct: false, text: "Savings account"},
                {id: 268, challengeId: 91, correct: false, text: "Checking account"},
                {id: 269, challengeId: 91, correct: false, text: "Money market account"},
                {id: 270, challengeId: 91, correct: true, text: "Certificate of Deposit (CD)"},
                {id: 271, challengeId: 92, correct: false, text: "Read aloud", audioSrc: "/bank6.mp3"},
                {id: 272, challengeId: 92, correct: true, text: "Got it"},
                {id: 273, challengeId: 93, correct: false, text: "SEC"},
                {id: 274, challengeId: 93, correct: true, text: "FDIC"},
                {id: 275, challengeId: 93, correct: false, text: "CFPB"},
                {id: 276, challengeId: 93, correct: false, text: "IRS"},
                {id: 277, challengeId: 94, correct: false, text: "Anti-money laundering laws"},
                {id: 278, challengeId: 94, correct: false, text: "Financial privacy regulations"},
                {id: 279, challengeId: 94, correct: true, text: "Consumer protection laws"},
                {id: 280, challengeId: 94, correct: false, text: "Capital adequacy requirements"},
                {id: 281, challengeId: 95, correct: false, text: "Read aloud", audioSrc: "/bank7.mp3"},
                {id: 282, challengeId: 95, correct: true, text: "Got it"},
                {id: 283, challengeId: 96, correct: true, text: "False"},
                {id: 284, challengeId: 96, correct: false, text: "True"},
                {id: 285, challengeId: 97, correct: false, text: "Read aloud", audioSrc: "/fin3.mp3"},
                {id: 286, challengeId: 97, correct: true, text: "Got it"},
                {id: 287, challengeId: 98, correct: false, text: "Reliable"},
                {id: 288, challengeId: 98, correct: true, text: "Relevant"},
                {id: 289, challengeId: 98, correct: false, text: "Rapid"},
                {id: 290, challengeId: 98, correct: false, text: "Resourceful"},
                {id: 291, challengeId: 99, correct: false, text: "Read aloud", audioSrc: "/fin4.mp3"},
                {id: 292, challengeId: 99, correct: true, text: "Got it"},
                {id: 293, challengeId: 100, correct: false, text: "Read aloud", audioSrc: "/fin5.mp3"},
                {id: 294, challengeId: 100, correct: true, text: "Got it"},
                {id: 295, challengeId: 101, correct: false, text: "I want to save some money for emergencies."},
                {id: 296, challengeId: 101, correct: false, text: "I want to save enough money to buy a car someday."},
                {id: 297, challengeId: 101, correct: false, text: "I want to save money for a vacation sometime in the future."},
                {id: 298, challengeId: 101, correct: true, text: "I want to save $3,000 for an emergency fund by setting aside $150 from each biweekly paycheck for 10 weeks"},
                {id: 299, challengeId: 102, correct: false, text: "Read aloud", audioSrc: "/fin6.mp3"},
                {id: 300, challengeId: 102, correct: true, text: "Got it"},
                // {id: 301, challengeId: 104, correct: false, text: "Medium term goal"},
                // {id: 302, challengeId: 104, correct: false, text: "Long term goal"},
                // {id: 303, challengeId: 104, correct: true, text: "Short term goal"},
                // {id: 304, challengeId: 104, correct: false, text: "None"},
                {id: 305, challengeId: 105, correct: false, text: "Read aloud", audioSrc: "/ins1.mp3"},
                {id: 306, challengeId: 105, correct: true, text: "Got it"},
                {id: 307, challengeId: 106, correct: false, text: "Read aloud", audioSrc: "/ins2.mp3"},
                {id: 308, challengeId: 106, correct: true, text: "Got it"},
                {id: 309, challengeId: 107, correct: false, text: "The amount paid annually to the insurance company"},
                {id: 310, challengeId: 107, correct: false, text: "The fixed fee paid for each covered service"},
                {id: 311, challengeId: 107, correct: false, text: "The maximum payout limit for a claim"},
                {id: 312, challengeId: 107, correct: true, text: "The initial out-of-pocket amount before insurance coverage starts"},
                {id: 313, challengeId: 108, correct: false, text: "Read aloud", audioSrc: "/ins3.mp3"},
                {id: 314, challengeId: 108, correct: true, text: "Got it"},
                {id: 315, challengeId: 109, correct: false, text: "By calculating the maximum payout for a claim"},
                {id: 316, challengeId: 109, correct: false, text: "By estimating the likelihood of a covered loss based on factors like age and location"},
                {id: 317, challengeId: 109, correct: true, text: "By setting a fixed fee for each covered service"},
                {id: 318, challengeId: 109, correct: false, text: "By determining the initial out-of-pocket amount before coverage starts"},
                {id: 319, challengeId: 110, correct: false, text: "Read aloud", audioSrc: "/ins4.mp3"},
                {id: 320, challengeId: 110, correct: true, text: "Got it"},
                {id: 321, challengeId: 111, correct: true, text: "The underwriter"},
                {id: 322, challengeId: 111, correct: false, text: "The insured"},
                {id: 323, challengeId: 111, correct: false, text: "The insurer"},
                {id: 324, challengeId: 111, correct: false, text: "The agent"},
                {id: 325, challengeId: 112, correct: false, text: "Read aloud", audioSrc: "/ins5.mp3"},
                {id: 326, challengeId: 112, correct: true, text: "Got it"},
                {id: 327, challengeId: 113, correct: false, text: "To avoid paying premiums"},
                {id: 328, challengeId: 113, correct: false, text: "To receive free medical care"},
                {id: 329, challengeId: 113, correct: true, text: "To help cover the cost of medical expenses"},
                {id: 330, challengeId: 113, correct: false, text: "To choose specific doctors for treatment"},
                {id: 331, challengeId: 114, correct: false, text: "Read aloud", audioSrc: "/ret3.mp3"},
                {id: 332, challengeId: 114, correct: true, text: "Got it"},
                {id: 333, challengeId: 115, correct: false, text: "To have more time for traveling"},
                {id: 334, challengeId: 115, correct: false, text: "To quit full-time work sooner"},
                {id: 335, challengeId: 115, correct: true, text: "To achieve greater financial security and flexibility"},
                {id: 336, challengeId: 115, correct: false, text: "To delay retirement age"},
                {id: 337, challengeId: 116, correct: false, text: "Read aloud", audioSrc: "/ret4.mp3"},
                {id: 338, challengeId: 116, correct: true, text: "Got it"},
                {id: 339, challengeId: 117, correct: true, text: "To have more flexibility in retirement plans"},
                {id: 340, challengeId: 117, correct: false, text: "To quit working entirely and travel"},
                {id: 341, challengeId: 117, correct: false, text: "To avoid thinking about retirement"},
                {id: 342, challengeId: 117, correct: false, text: "To focus solely on current expenses"},
                {id: 343, challengeId: 118, correct: false, text: "It decreases the value of investments"},
                {id: 344, challengeId: 118, correct: false, text: "It has no effect on retirement savings"},
                {id: 345, challengeId: 118, correct: true, text: "It increases the potential growth of investments"},
                {id: 346, challengeId: 118, correct: false, text: "It reduces the need for retirement planning"},
                {id: 347, challengeId: 119, correct: false, text: "Read aloud", audioSrc: "/ret5.mp3"},
                {id: 348, challengeId: 119, correct: true, text: "Got it"},
                {id: 349, challengeId: 120, correct: false, text: "Owning a large house"},
                {id: 350, challengeId: 120, correct: false, text: "Traveling extensively"},
                {id: 351, challengeId: 120, correct: false, text: "Pursuing hobbies full-time"},
                {id: 352, challengeId: 120, correct: true, text: "Having a steady source of income"},
                {id: 353, challengeId: 121, correct: false, text: "Read aloud", audioSrc: "/ret6.mp3"},
                {id: 354, challengeId: 121, correct: true, text: "Got it"},
                {id: 355, challengeId: 122, correct: true, text: "Having enough income and savings"},
                {id: 356, challengeId: 122, correct: false, text: "Owning a large house"},
                {id: 357, challengeId: 122, correct: true, text: "Pursuing hobbies full-time"},
                {id: 358, challengeId: 122, correct: false, text: "Traveling extensively"},
        ]);

       

        console.log("Seeding Finished");
    } catch (error) {
        console.error("Failed to seed the database", error);
    }
};

main();